---
# tasks/lab1_hosts.yml
- hosts: hostfile
  gather_facts: False

  tasks:
    #retrieves data from Server
    - name: retrieve floatingip-information
      command: "neutron floatingip-list --os-cacert /home/likewise-open/SINCLOUD/nbradford/signing-ca-chain.pem --os-password P@ssw0rd --os-tenant-name lab-aburke-01 --os-username aburke --os-auth-url https://cloud.singapore.local:5000/v2.0 | awk '{print$4,$6}' | grep -v id | grep -v fixed_ip_address"
      when: ansible_os_family == "
      register: floating_ips
    #Copies local template and makes it host file
    - name: install lab-01 host file
      command: "cp /Users/aburke/Documents/Git/ansible-playbooks/hostfile/tasks/files/01-hosts.ansible /etc/hosts"
      become: true
    #Test connectivity. Failure will cause script to halt.
    - name: test connectivity
      command: "ping nsxmgr-01a.corp.local -c 1"