---
# tasks/lab1_hosts.yml
- hosts: self
  gather_facts: False

  tasks:
    - name: install lab-01 host file
      command: "cp /Users/aburke/Documents/Ansible/hostfile/tasks/files/01-hosts.ansible /etc/hosts"
      become: true